version: '3.7' 
services: 
  web: 
    build: app 
    ports: 
      - '8000:8000'
    networks:
      - selenium-grid

  selenium-node-chrome:
    image: selenium/node-chrome:89.0
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "6900:5900"
    networks:
      - selenium-grid

  selenium-hub:
    image: selenium/hub:4.0.0
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
    networks:
      - selenium-grid
      
networks:
  selenium-grid: